---
# tasks file for mysql
# Debian
- name: Install Mysql package
  apt: name{{ item }} state=present
  with_items:
  - python3-mysqldb
  - python-semanage
  - python3-pymysql

- name: Configure SELinux to start on any port
  seebolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux.status == "enabled"
 
- name: Create MySQL configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mysql

- name: Start MySQL Service
  service: name=mysqld state=started enabled=yes
